/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package attendancemanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class mainFrame extends javax.swing.JFrame {
    /**
     * Creates new form frmMain
     */
    public mainFrame() {
        //setTitle("ITCSIU21166-Nguyen Quoc Thai Bao");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAll = new javax.swing.JButton();
        btnShow1 = new javax.swing.JButton();
        btnEligible = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15));

        jPanel1.setFocusCycleRoot(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 115));

        btnAll.setText("Show all Student");
        btnAll.setPreferredSize(new java.awt.Dimension(150, 25));
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnAll);

        btnShow1.setText("Show 1 Student");
        btnShow1.setPreferredSize(new java.awt.Dimension(150, 25));
        btnShow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShow1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnShow1);

        btnEligible.setText("Show eligible "
            + "Student");
        btnEligible.setOpaque(true);
        btnEligible.setPreferredSize(new java.awt.Dimension(150, 45));
        btnEligible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEligibleActionPerformed(evt);
            }
        });
        jPanel1.add(btnEligible);

        getContentPane().add(jPanel1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(750, 400));
        jScrollPane1.setRequestFocusEnabled(false);

        txtResult.setColumns(20);
        txtResult.setRows(5);
        txtResult.setPreferredSize(jScrollPane1.size());
        jScrollPane1.setViewportView(txtResult);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed

        txtResult.selectAll();
        txtResult.replaceSelection("");
        String connectionUrl = "jdbc:sqlserver://localhost:1434;databaseName=Examination Management System;user=sa;password=Baogpmn123";

        try (Connection con = DriverManager.getConnection(connectionUrl);  
             java.sql.Statement stmt = con.createStatement();) {
            String SQL = "Select StudentID as ID, LastName + ' ' + MiddleName as [Last Name], FirstName as Name, Dob, Phone From Student";
            ResultSet rs = stmt.executeQuery(SQL);
            StringBuilder results = new StringBuilder();
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            for (int i = 1; i <= numberOfColumns; i++) {
                results.append(metaData.getColumnName(i)).append("\t");
            }
            results.append("\n");
            
            while (rs.next()) {
                for (int i = 1; i <= numberOfColumns; i++) {
                    results.append(rs.getObject(i)).append("\t");
                }                
                results.append("\n");
            }
            txtResult.setText(results.toString());                       
        }
        catch (SQLException e) {
            txtResult.setText(e.getMessage());
        }
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnShow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShow1ActionPerformed
        txtResult.selectAll();
        txtResult.replaceSelection("");
        String connectionUrl = "jdbc:sqlserver://localhost:1434;databaseName=Examination Management System;user=sa;password=Baogpmn123";
        
        try (Connection con = DriverManager.getConnection(connectionUrl);  
             java.sql.Statement stmt = con.createStatement();) {
            
            String ID = JOptionPane.showInputDialog("Please enter a student ID:");
            if (ID.length() == 0) return;
            String SQL = "Select StudentID as ID, LastName + ' ' + MiddleName as [Last Name], FirstName as Name, Dob, Phone From Student Where StudentID = " + ID;
            ResultSet rs = stmt.executeQuery(SQL);
            StringBuilder results = new StringBuilder();
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            for (int i = 1; i <= numberOfColumns; i++) {
                results.append(metaData.getColumnName(i)).append("\t");
            }
            results.append("\n");
            
            while (rs.next()) {
                for (int i = 1; i <= numberOfColumns; i++) {
                    results.append(rs.getObject(i)).append("\t");
                }                
                results.append("\n");
            }
            txtResult.setText(results.toString());                       
        }
        catch (SQLException e) {
            txtResult.setText(e.getMessage());
        }
    }
//GEN-LAST:event_btnShow1ActionPerformed

    private void btnEligibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEligibleActionPerformed
        txtResult.selectAll();
        txtResult.replaceSelection("");
        String connectionUrl = "jdbc:sqlserver://localhost:1434;databaseName=Examination Management System;user=sa;password=Baogpmn123";
        
        try (Connection con = DriverManager.getConnection(connectionUrl);  
             java.sql.Statement stmt = con.createStatement();) {
            
            String ID = JOptionPane.showInputDialog("Please enter a Course ID: ");
            String SQL;
            SQL = "Select";
            ResultSet rs = stmt.executeQuery(SQL);
            StringBuilder results = new StringBuilder();
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            for (int i = 1; i <= numberOfColumns; i++) {
                results.append(metaData.getColumnName(i)).append("\t");
            }
            results.append("\n");
            
            while (rs.next()) {
                for (int i = 1; i <= numberOfColumns; i++) {
                    results.append(rs.getObject(i)).append("\t");
                }                
                results.append("\n");
            }
            txtResult.setText(results.toString());                       
        }
        catch (SQLException e) {
            txtResult.setText(e.getMessage());
        }
    }//GEN-LAST:event_btnEligibleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        mainFrame frame = new mainFrame();
        frame.setVisible(true);
        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnEligible;
    private javax.swing.JButton btnShow1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
